name: common-base

dependencies:
  - conda-forge::cudatoolkit
  - conda-forge::cudnn
  - conda-forge::tritonclient==2.21.0
  - conda-forge::tritonclient[http]
  - pip
  - pip:
    - -e /app/api_utils/