name: common-base

dependencies:
  - conda-forge::cudatoolkit
  - conda-forge::cudnn
  - pip
  - setuptools
  - wheel
  - pip:
    - -e /app/api_utils/
    - tritonclient[http]
    - tritonclient==2.21.0