version: "3"

services:
  gladia:
    image: gladiaio/gladia:latest
    environment:
      - TRITON_SERVER_PORT_HTTP=8000
      - TRITON_SERVER_URL=0.0.0.0:8000
      - TRITON_LAZY_DOWNLOAD=false
      - TRITON_MODELS_PATH=/tmp/gladia/triton
    volumes:
      - /tmp/gladia/:/tmp/gladia/
    container_name: gladia
    shm_size: '5gb'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
